### ISSUE TITLE
Add commented out configuration to use forward secrecy

### ISSUE THREAD

**Issue by opi** [YunoHost/yunohost-config-metronome#2]
See https://github.com/YunoHost/moulinette-yunohost/issues/36

> But as in the nginx configuration we can comment out the right lines in the configuration to 
> help administrator activate DH param.

@dattaz : Do you have a working configuration for metronome ?

**Comment by dattaz** [comment]
No

**Comment by alexAubin** [comment]
Closing because probably outdated
